# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.define "Backend"
  config.vm.provider "virtualbox" do |vb|
    vb.name = 'Backend'
  end
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provision "docker"
  config.vm.provision "shell" do |s|
    s.path = "provision.sh"
  end
  
end
